### ISSUE TITLE
Handle "back" function by hitting backspace

### ISSUE THREAD

**Issue by rudzboy** [FrazzIe/model-menu#1]
Hi ! First of all, great job of this feature ;)

May I suggest a small enhancement of the controls and behaviour of the menu ?

Handle "back" function by hitting backspace
No "return" buttons on each panel ;)

As a working example on a other script : 

https://github.com/Kyominii/Cops_FiveM/blob/master/police/menupolice.lua#L421

Would you mind having a look and try to use this ?

Then your script will be absolulty perfect I think !
Keep up the good work ;)

**Comment by FrazzIe** [comment]
It took nearly a month but here ya go
